### ISSUE TITLE
Routing problems

### ISSUE THREAD

**Issue by AlMuz** [rubensrocha/fruit-farm#1]
I'm trying to change page and in url is changing but template does not.
![screenshot from 2018-05-11 16-21-13](https://user-images.githubusercontent.com/29034104/39926360-a6523ace-5537-11e8-9f98-1729e6119814.png)
/stat page and it looks like like main page. 
So question is, this is only on my pc this problem?
I'm starting server in terminal with php -S localhost:port
I used other versions of this script several years ago and it worked, and now it does not work

**Comment by AlMuz** [comment]
PS if you want, i can make translation on Russian language

**Comment by AlMuz** [comment]
And I also tested the site on Windows with  terminal and there was the same problem

**Comment by rubensrocha** [comment]
I tested on localhost using Xampp 3.2.2 (php 7.2) and everything works normally. Make sure you have enabled mod_rewrite and use a domain for this(Eg: yoursite.com, projec.dev or app.projectname), create a alias if necessary, maybe don't work on subfolders(Eg.: localhost/foldername).

My Xampp configs:
Directory: xampp/htdocs/FF
Alias: http://app.fruitfarm/

httpd-vhosts config:
<VirtualHost *:80>
	ServerName app.fruitfarm
	DocumentRoot "F:\xampp\htdocs\ff"
	<Directory  "F:\xampp\htdocs\ff/">
		Options +Indexes +Includes +FollowSymLinks +MultiViews
		AllowOverride All
		Require local
	</Directory>
</VirtualHost>

Yes, you can translate to Russian and post here (or make a pull request from the file) that I will include it in the script. :-)
