### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by AlMuz** [rubensrocha/fruit-farm#3]
Hey i did [pull request](https://github.com/rubensrocha/fruit-farm/pull/2) with translations, check it. 
I have some things to improve. 
Please, make language picker for admin, there is translations for admin panel, but i didnt find this picker.
After that please [check this line](https://github.com/rubensrocha/fruit-farm/blob/master/pages/_signup.php#L48)  and fix it. You are comparing nonMD5 password with MD5 password.
And also delete some validation on this page from 45 - 47, because you already validated inputs with your GUMP.
` <input type="email" value="<?=(isset($_POST["email"])) ? $_POST["email"] : false; ?>" class="form-control">` add there name="email" because as i understand without it there will be error, what email is require.
And the last thing if im trying to login and did a mistake in form after loading modal with error description is closed. Need to change this thing a little bit.

**Comment by rubensrocha** [comment]
Hi friend.
I merged your pull request, thanks for your contribuition. :-)
You can change default admin lang in Settings->General->Admin Language.
I'll correct the validation on line 48.
On lines 45->47 it's necessary because of translation, or GUMP will print error messages only in English.
About the modal, I'm not sure how to make it appear automatically after the login attempt fails. :( xD

**Comment by AlMuz** [comment]
Maybe this error div we can place somewhere in right corner and make with absolute position  or smth like this

**Comment by AlMuz** [comment]
i will try to clean up project from unused files, beautify some js files and i found error on payment page in console.

**Comment by rubensrocha** [comment]
Ok, send a pull request again if you fix any other bug. Thanks for your contribution.

**Comment by AlMuz** [comment]
![image](https://user-images.githubusercontent.com/29034104/41291963-ce60ba82-6e59-11e8-8c90-1b42f931de60.png)
maybe something like this... 
but this notification will be only after unsuccessful login, on recovery page, on registration page.

**Comment by AlMuz** [comment]
[this is pull request for feature above](https://github.com/rubensrocha/fruit-farm/pull/4)

**Comment by AlMuz** [comment]
Hey, check this [pull request](https://github.com/rubensrocha/fruit-farm/pull/5/)

**Comment by AlMuz** [comment]
And don't forget to add translations for [PT](https://github.com/rubensrocha/fruit-farm/commits/master/langs/pt.php)

**Comment by rubensrocha** [comment]
Merged. :-)
